project_id = "dhaccjvaeokriqooibmy"

[functions.verify-user-email]
verify_jwt = false

[functions.payment-webhook]
verify_jwt = false

[functions.initialize-balance]
verify_jwt = true

[functions.credit-balance]
verify_jwt = true

[functions.debit-balance]
verify_jwt = true
